version: '3'
services:
  fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
    volumes:
      - ./app_volume/alembic/versions:/internship-task/alembic/versions
      - ./app_volume/logs:/internship-task/logs/
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./db_volume/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: internship-task_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      LOG_DESTINATION: stderr
      LOGGING_COLLECTOR: "true"
      LOG_DIRECTORY: /var/log/postgresql
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    volumes:
      - ./rabbitmq_volume:/var/lib/rabbitmq
  celery:
    build: .
    command: celery -A statistic.worker worker --pool=asyncio --loglevel=INFO
    working_dir: /internship-task
    depends_on:
      - rabbitmq
      - db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
    env_file:
      - .env
    volumes:
      - .:/internship-task/

