[tool.poetry]
name = "task"
version = "0.1.0"
description = ""
authors = ["Author <viacheslau.bankousky@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
uvicorn = "^0.23.2"
httpx = "^0.25.0"
fastapi = "^0.115.6"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.37"}
aiosqlite = "^0.20.0"
alembic = "^1.14.1"
asyncpg = "^0.30.0"
pydantic = {extras = ["email"], version = "^2.10.6"}
pydantic-settings = "^2.7.1"
pyjwt = "^2.10.1"
passlib = "^1.7.4"
python-multipart = "^0.0.20"
celery = {extras = ["asyncio"], version = "^5.4.0"}


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pytest-alembic = "^0.10.7"
pytest-asyncio = "^0.21.1"
pytest-cov = "^4.1.0"
pytest-env = "^1.0.1"
pytest-httpx = "^0.26.0"
pytest-mock = "^3.11.1"
pytest-mock-server = "^0.3.0"
pytest-xdist = "^3.3.1"
wemake-python-styleguide = "^1.0.0"
black = "^24.10.0"
isort = "^6.0.0"
mypy = "^1.14.1"
pre-commit = "^4.1.0"
flake8-docstrings = "^1.7.0"
pydocstyle = "^6.3.0"
flake8-bugbear = "^24.12.12"
darglint = "^1.8.1"
types-passlib = "^1.7.7.20241221"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
strict_optional = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:'crypt' is deprecated"
]
