from core.base_exception import BaseAPIException


class TransactionForBlockedUserException(BaseAPIException): ...


class TransactionAlreadyRollbackedException(BaseAPIException): ...


class NegativeBalanceException(BaseAPIException): ...


class TransactionsNotFoundException(BaseAPIException): ...
