"""
This module manages the application's exception handling.

The `ErrorHandler` class catches various types of exceptions, providing an
appropriate response for each.
It handles the exceptions that could occur during the handling of a request,
and provides an error response corresponding to the type of exception that
occurred.
"""

from typing import Awaitable, Callable

from fastapi import Request, Response, status

from api_utils.generate_error_response import generate_error_response
from core.base_exception import BaseAPIException
from core.logger_configuration import app_logger


class ErrorHandler:
    """
    The `ErrorHandler` class for centralized exception handling.

    This class provides a method to intercept and process FastAPI requests,
    catching any exceptions that occur during the request lifecycle.
    It ensures a consistent and user-friendly error response is generated
    for each type of exception, whether it is a custom application exception
    or an unexpected server error.

    Typical usage involves adding the `ErrorHandler` to middleware to manage
    exceptions globally.
    The class distinguishes between custom `BaseAPIException` errors and
    general exceptions, logging the errors and returning an appropriate
    response for each case.
    """

    @classmethod
    async def handle_errors(
        cls,
        request: Request,
        call_next: Callable[[Request], Awaitable[Response]],
    ) -> Response:
        """Handle a FastAPI request and catch any exceptions that occur.

        Args:
            request (Request):
                The incoming HTTP request.
            call_next (Callable):
                A callable that will process the request and generate the
                response.

        Returns:
            The HTTP response generated by the callable 'call_next' or an error
            response if an exception occurs.
        """
        try:
            return await call_next(request)
        except Exception as exc:
            app_logger.exception(f"An error occurred: {exc}")
            if isinstance(exc, BaseAPIException):
                return generate_error_response(
                    status_code=exc.status_code,
                    error_message=exc.message,
                )
            return generate_error_response(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                error_message="Something went wrong on the server side",
            )
